from pydantic import BaseModel

class AutoGeneratedResponse(BaseModel):
    queryId: str
    answer: str
    userId: str
    timestamp: int
    deleted: bool
    supportVerified: bool
    aiGenerated: bool
    upvotes: int